version: "1.0"
info:
  model: int-scaffold
packages:
- name: ExternalGitPrivateProjectProject
  gitServerName: SomaIBM
  gitUrl: https://github.com/Somasekhar-K-IBM
  gitUsername: Somasekhar-K-IBM
  gitBranch: main
